//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecretAgent {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label LabelAgentInfo;
		
		protected System.Web.UI.WebControls.TextBox TextBoxName;
		
		protected System.Web.UI.WebControls.Label LabelName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxLang1;
		
		protected System.Web.UI.WebControls.Label LabelLang1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxLang2;
		
		protected System.Web.UI.WebControls.Label LabelLang2;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label LabelNo_Agents;
		
		protected System.Web.UI.WebControls.Button button2;
		
		protected System.Web.UI.WebControls.ListBox ListBoxAgents;
		
		protected System.Web.UI.WebControls.Button button3;
		
		protected System.Web.UI.WebControls.Label HandleAgent;
		
		protected System.Web.UI.WebControls.TextBox EditName;
		
		protected System.Web.UI.WebControls.TextBox EditLang1;
		
		protected System.Web.UI.WebControls.TextBox EditLang2;
		
		protected System.Web.UI.WebControls.TextBox EditCeasarText;
		
		protected System.Web.UI.WebControls.TextBox EditCeasarKey;
		
		protected System.Web.UI.WebControls.Button button4;
	}
}
